backup:
  clean_on_failure: true
  skip_backup_directory: false
  path: /path/to/backup/directory
  projects_folder: path/to/projects.d/
  projects:
    00_project:
      name: project
      backup_dir: some_name
      00_rsync:
        plugin: local_rsync
        paths:
          - path: /path/to/dir
            exclude:
            - path/to/exclude
            - path/to/exclude2
            backup_dir: /path/to/create
          - path: /path/to/dir2
    01_project:
      00_docker:
        plugin: docker
        container: docker_container
        action: stop
      01_rsync:
        plugin: local_rsync
        paths:
          - /path/to/dir
      02_remove:
        plugin: remove
        paths:
          - MediaCover
      03_docker:
        plugin: docker
        container: docker_container
        action: start
    02_project:
      00_docker_compose:
        plugin: docker_compose
        action: build
        path: /full/path/to/docker-compose.yml
        stack_name: stackName
        run_as:
          uid: 1000
          gid: 1000
      01_docker_compose:
        plugin: docker_compose
        action: pull
        path: /full/path/to/docker-compose.yml
        run_as:
          uid: 1000
          gid: 1000
        stack_name: stackName
      02_docker_compose:
        plugin: docker_compose
        action: down
        path: /full/path/to/docker-compose.yml
        stack_name: stackName
        run_as:
          uid: 1000
          gid: 1000
      03_rsync:
        plugin: local_rsync
        paths:
          - /path/to/dir
      04_docker_compose:
        plugin: docker_compose
        action: up
        path: /full/path/to/docker-compose.yml
        stack_name: stackName
        run_as:
          uid: 1000
          gid: 1000
    03_project:
      00_compress:
        plugin: compress
        do_compress: true
    04_project:
      00_limit:
        plugin: limit_backups
        total: 7
