backup:
  clean_on_failure: true
  compress_only: false
  path: /path/to/backup/directory
  projects_folder: path/to/projects.d/
  projects:
    00_project:
      00_rsync:
        plugin: local_rsync
        paths:
          - path: /path/to/dir
            exclude:
            - path/to/exclude
            - path/to/exclude2
          - path: /path/to/dir2
    01_project:
      00_docker:
        plugin: docker
        container: docker_container
        action: stop
      01_rsync:
        plugin: local_rsync
        paths:
          - /path/to/dir
      02_remove:
        plugin: remove
        paths:
          - MediaCover
      03_docker:
        plugin: docker
        container: docker_container
        action: start
    02_project:
      00_compress:
        plugin: compress
        do_compress: true
