backup:
  compress: true
  path: /path/to/backup/directory
  order:
    a: project
    b: project2
  projects:
    project:
      steps:
        a: rsync1
      ops:
        rsync1:
          plugin: local_rsync
          paths:
            - /path/to/dir
            - /path/to/dir2
    project2:
      steps:
        a: docker1
        b: rsync1
        c: docker2
      ops:
        docker1:
          plugin: docker
          container: docker_container
          action: stop
        rsync1:
          plugin: local_rsync
          paths:
            - /path/to/dir
        docker2:
          plugin: docker
          container: docker_container
          action: start
