# tells ej-backup that this is a backup configuration
backup:
  # clean_on_failure: true - remove the parent backup directory on failure during backup
  #                   false - leave the parent backup directory in place on failure during backup
  clean_on_failure: true
  # skip_backup_directory: true - skip creating a parent backup directory
  #                                 * This is helpful for operations where files won't be copied into a backup
  #                                   or during compressing previous backups
  #                        false - don't skip creating a parent backup directory
  skip_backup_directory: false
  # path: path to a directory that will hold backups
  #         * This is where parent backup directories will be created in the format of 2023-06-01_00-00-00
  #         * resultant: /path/to/backup/directory/2023-06-01_00-00-00
  path: /path/to/backup/directory
  # notifiers_folder: path, relative to the backup configuration (backup.yaml) that holds notifier configurations.
  #                   Only one configuration is supported per notifier currently.
  notifiers_folder: path/to/notifiers.d/
  # projects_folder: path, relative to the backup configuration (backup.yaml) that holds project configurations.
  projects_folder: path/to/projects.d/
