name: project
backup_dir: some_name
00_docker:
  plugin: docker
  container: docker_container
  action: stop
01_rsync:
  plugin: local_rsync
  paths:
    - path: /path/to/dir
      backup_dir: holder/to/create/in/backup
02_remove:
  plugin: remove
  paths:
    - somePath/
03_docker:
  plugin: docker
  container: docker_container
  action: start
